%SKELETON
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.identifier }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - workload
    - gx
    - guardian
spec:
  type: workload
  lifecycle: experimental
  owner: ${{ values.developmentGroup }}
  system: ${{ values.parentRef }}
  domain: ${{ values.domain }}
  mesh:
    name: ${{ values.name }}
    fullyQualifiedName: ${{ values.domainName }} - ${{ values.parentRefName }} - version ${{ values.identifier.split(".")[2] }} - ${{ values.name }}
    description: ${{ values.description }}
    kind: workload
    version: 0.0.0
    infrastructureTemplateId: ${{ values.infrastructureTemplateId }}
    useCaseTemplateId: ${{ values.useCaseTemplateId }}
    dependsOn: {% if values.dependsOn | length > 0 %}{% for i in values.dependsOn %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    platform: AWS
    technology: Great Expectations
    workloadType: Internal Process
    connectionType: HOUSEKEEPING
    tags: {% if values.tags | length > 0 %}{% for i in values.tags %}
      - tagFQN: ${{ i }}
        source: Tag
        labelType: Manual
        state: Confirmed{% endfor %}{% else %}[]{% endif %}
    readsFrom: {% if values.readsFrom | length > 0 %}{% for i in values.readsFrom %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    __dataContractGuardianSpec:
      guards: {% if values.dataContracts | length > 0 %}{% for i in values.dataContracts %}
        - dataContractId: ${{ i }}{% endfor %}{% else %}[]{% endif %}
    specific: {}
